[2025-09-23T14:47:26.588+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T14:47:26.593+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inpainting_pipeline.train_model scheduled__2025-09-22T00:00:00+00:00 [queued]>
[2025-09-23T14:47:26.596+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inpainting_pipeline.train_model scheduled__2025-09-22T00:00:00+00:00 [queued]>
[2025-09-23T14:47:26.596+0300] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-09-23T14:47:26.665+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-22 00:00:00+00:00
[2025-09-23T14:47:26.670+0300] {standard_task_runner.py:72} INFO - Started process 81397 to run task
[2025-09-23T14:47:26.675+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'inpainting_pipeline', 'train_model', 'scheduled__2025-09-22T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/inpainting_pipeline.py', '--cfg-path', '/var/folders/h3/mldqkd0s4gs3d0z9_b487vs00000gn/T/tmpn01doqut']
[2025-09-23T14:47:26.677+0300] {standard_task_runner.py:105} INFO - Job 21: Subtask train_model
[2025-09-23T14:47:26.707+0300] {task_command.py:467} INFO - Running <TaskInstance: inpainting_pipeline.train_model scheduled__2025-09-22T00:00:00+00:00 [running]> on host macbook-air-alexander-2.local
[2025-09-23T14:47:26.736+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-student' AIRFLOW_CTX_DAG_ID='inpainting_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-22T00:00:00+00:00'
[2025-09-23T14:47:26.736+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-23T14:47:26.737+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-23T14:47:26.737+0300] {logging_mixin.py:190} INFO - Current task name:train_model state:running start_date:2025-09-23 11:47:26.594163+00:00
[2025-09-23T14:47:26.738+0300] {logging_mixin.py:190} INFO - Dag name:inpainting_pipeline and current dag run status:running
[2025-09-23T14:47:26.738+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-23T14:47:26.738+0300] {inpainting_pipeline.py:12} INFO - Running command: python3 /Users/vozamhcak/celeba-inpainting/code/models/train.py
[2025-09-23T14:47:28.478+0300] {inpainting_pipeline.py:21} INFO - STDOUT:
[INFO] Using device: cpu

[2025-09-23T14:47:28.479+0300] {inpainting_pipeline.py:23} ERROR - STDERR:
Traceback (most recent call last):
  File "/Users/vozamhcak/celeba-inpainting/code/models/train.py", line 30, in <module>
    dataset = datasets.ImageFolder(root=DATA_DIR, transform=transform)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 328, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 150, in __init__
    samples = self.make_dataset(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 203, in make_dataset
    return make_dataset(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 104, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes test, train. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

[2025-09-23T14:47:28.479+0300] {inpainting_pipeline.py:26} ERROR - Command failed with return code 1
[2025-09-23T14:47:28.480+0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 35, in train_model
    run_script(f"python3 {script_path}")
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 24, in run_script
    result.check_returncode()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'python3 /Users/vozamhcak/celeba-inpainting/code/models/train.py' returned non-zero exit status 1.
[2025-09-23T14:47:28.485+0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-23T14:47:28.486+0300] {logging_mixin.py:190} INFO - Task start:2025-09-23 11:47:26.594163+00:00 end:2025-09-23 11:47:28.485537+00:00 duration:1.891374
[2025-09-23T14:47:28.486+0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_model> dag:<DAG: inpainting_pipeline> dagrun:<DagRun inpainting_pipeline @ 2025-09-22 00:00:00+00:00: scheduled__2025-09-22T00:00:00+00:00, state:running, queued_at: 2025-09-23 09:53:53.075372+00:00. externally triggered: False>
[2025-09-23T14:47:28.486+0300] {logging_mixin.py:190} INFO - Failure caused by Command 'python3 /Users/vozamhcak/celeba-inpainting/code/models/train.py' returned non-zero exit status 1.
[2025-09-23T14:47:28.486+0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=inpainting_pipeline, task_id=train_model, run_id=scheduled__2025-09-22T00:00:00+00:00, execution_date=20250922T000000, start_date=20250923T114726, end_date=20250923T114728
[2025-09-23T14:47:28.490+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-23T14:47:28.490+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task train_model (Command 'python3 /Users/vozamhcak/celeba-inpainting/code/models/train.py' returned non-zero exit status 1.; 81397)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 35, in train_model
    run_script(f"python3 {script_path}")
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 24, in run_script
    result.check_returncode()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'python3 /Users/vozamhcak/celeba-inpainting/code/models/train.py' returned non-zero exit status 1.
[2025-09-23T14:47:28.533+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-23T14:47:28.542+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T14:47:28.543+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
