[2025-09-23T14:47:47.065+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T14:47:47.069+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inpainting_pipeline.deploy_api manual__2025-09-23T11:47:26.523389+00:00 [queued]>
[2025-09-23T14:47:47.071+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inpainting_pipeline.deploy_api manual__2025-09-23T11:47:26.523389+00:00 [queued]>
[2025-09-23T14:47:47.071+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-09-23T14:47:47.111+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): deploy_api> on 2025-09-23 11:47:26.523389+00:00
[2025-09-23T14:47:47.114+0300] {standard_task_runner.py:72} INFO - Started process 81527 to run task
[2025-09-23T14:47:47.117+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'inpainting_pipeline', 'deploy_api', 'manual__2025-09-23T11:47:26.523389+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/inpainting_pipeline.py', '--cfg-path', '/var/folders/h3/mldqkd0s4gs3d0z9_b487vs00000gn/T/tmp3y_bkpm3']
[2025-09-23T14:47:47.117+0300] {standard_task_runner.py:105} INFO - Job 25: Subtask deploy_api
[2025-09-23T14:47:47.132+0300] {task_command.py:467} INFO - Running <TaskInstance: inpainting_pipeline.deploy_api manual__2025-09-23T11:47:26.523389+00:00 [running]> on host macbook-air-alexander-2.local
[2025-09-23T14:47:47.151+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-student' AIRFLOW_CTX_DAG_ID='inpainting_pipeline' AIRFLOW_CTX_TASK_ID='deploy_api' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T11:47:26.523389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-23T11:47:26.523389+00:00'
[2025-09-23T14:47:47.151+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-23T14:47:47.151+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-23T14:47:47.152+0300] {logging_mixin.py:190} INFO - Current task name:deploy_api state:running start_date:2025-09-23 11:47:47.070020+00:00
[2025-09-23T14:47:47.152+0300] {logging_mixin.py:190} INFO - Dag name:inpainting_pipeline and current dag run status:running
[2025-09-23T14:47:47.152+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-23T14:47:47.152+0300] {inpainting_pipeline.py:12} INFO - Running command: docker compose -f /Users/vozamhcak/celeba-inpainting/docker-compose.yml up -d --build
[2025-09-23T14:47:47.583+0300] {inpainting_pipeline.py:21} INFO - STDOUT:

[2025-09-23T14:47:47.586+0300] {inpainting_pipeline.py:23} ERROR - STDERR:
time="2025-09-23T14:47:47+03:00" level=warning msg="/Users/vozamhcak/celeba-inpainting/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
unable to get image 'celeba-app:latest': Cannot connect to the Docker daemon at unix:///Users/vozamhcak/.docker/run/docker.sock. Is the docker daemon running?

[2025-09-23T14:47:47.587+0300] {inpainting_pipeline.py:26} ERROR - Command failed with return code 1
[2025-09-23T14:47:47.589+0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 39, in deploy_api
    run_script(f"docker compose -f {compose_path} up -d --build", cwd=BASE_DIR)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 24, in run_script
    result.check_returncode()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'docker compose -f /Users/vozamhcak/celeba-inpainting/docker-compose.yml up -d --build' returned non-zero exit status 1.
[2025-09-23T14:47:47.606+0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-23T14:47:47.607+0300] {logging_mixin.py:190} INFO - Task start:2025-09-23 11:47:47.070020+00:00 end:2025-09-23 11:47:47.605809+00:00 duration:0.535789
[2025-09-23T14:47:47.607+0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): deploy_api> dag:<DAG: inpainting_pipeline> dagrun:<DagRun inpainting_pipeline @ 2025-09-23 11:47:26.523389+00:00: manual__2025-09-23T11:47:26.523389+00:00, state:running, queued_at: 2025-09-23 11:47:26.530567+00:00. externally triggered: True>
[2025-09-23T14:47:47.608+0300] {logging_mixin.py:190} INFO - Failure caused by Command 'docker compose -f /Users/vozamhcak/celeba-inpainting/docker-compose.yml up -d --build' returned non-zero exit status 1.
[2025-09-23T14:47:47.609+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=inpainting_pipeline, task_id=deploy_api, run_id=manual__2025-09-23T11:47:26.523389+00:00, execution_date=20250923T114726, start_date=20250923T114747, end_date=20250923T114747
[2025-09-23T14:47:47.619+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-23T14:47:47.620+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task deploy_api (Command 'docker compose -f /Users/vozamhcak/celeba-inpainting/docker-compose.yml up -d --build' returned non-zero exit status 1.; 81527)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 39, in deploy_api
    run_script(f"docker compose -f {compose_path} up -d --build", cwd=BASE_DIR)
  File "/Users/vozamhcak/celeba-inpainting/airflow/dags/inpainting_pipeline.py", line 24, in run_script
    result.check_returncode()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'docker compose -f /Users/vozamhcak/celeba-inpainting/docker-compose.yml up -d --build' returned non-zero exit status 1.
[2025-09-23T14:47:47.663+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-23T14:47:47.675+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T14:47:47.675+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
